services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: cloudsigma.com/php
    container_name: ${APP_NAME}-backend
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: backend
      SERVICE_TAGS: dev
    working_dir: /var/www/api/
    volumes:
      - ./:/var/www/api/
    networks:
      - app-network

  frontend:
    stdin_open: true
    container_name: ${APP_NAME}-frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ../frontend:/var/www/html/
    networks:
      - app-network

  webserver:
    depends_on:
      - backend
      - frontend
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-webserver
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www/api/
    ports:
      - "80:80"
    networks:
      - app-network

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: ${APP_NAME}-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./mysql/volumes:/var/lib/mysql
    ports:
      - '8987:3306'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
