networks:
  backend:
    driver: bridge

services:
  nginx:
    image: nginx:alpine
    ports:
      - '82:80'
    volumes:
      - ../backend/src:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d

  php:
    build:
      context: ./php
      args:
        - PHP_VERSION=${PHP_VERSION}
    volumes:
      - ../backend/src:/var/www/html

  mysql:
    image: mysql:${MYSQL_VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./mysql/volumes:/var/lib/mysql
