services:
  nginx:
    image: nginx:alpine
    ports:
      - '82:80'
    volumes:
      - ../backend:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d

  # node:
  #   build:
  #     context: ./node
  #     target: ${STAGE}
  #     args:
  #       - NODE_VERSION=${NODE_VERSION}
  #   volumes:
  #     - ${PROJECT_PATH_FRONTEND}:/home/node/app
  #   ports:
  #     - 84:80

  # php:
  #   build:
  #     context: ./php
  #     args:
  #       - PHP_VERSION=${PHP_VERSION}
  #   volumes:
  #     - ../backend:/var/www/html

  # mysql:
  #   image: mysql:${MYSQL_VERSION}
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #     - MYSQL_DATABASE=${MYSQL_DATABASE}
  #     - MYSQL_USER=${MYSQL_USER}
  #     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  #   volumes:
  #     - ./mysql/volumes:/var/lib/mysql
